GET http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpIiwiaWQiOiI2MDMwMGJjM2Q0ZDA5ZTEyODBmMDZkMTQiLCJpYXQiOjE2MTM4MzYzNDF9.S_4m85ydMd5cNDZG873CcNnhWYrFz3AUSfEHpwYhrt0
